logging:
  level:
    org.springframework.security.web: DEBUG

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    enabled: false
#    main:
#      web-application-type: reactive
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  tracing:
    sampling:
      probability: 1.0