server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001

management:
  tracing:
    sampling:
      probability: 1.0