spring:
  application:
    name: blog-service
  config:
    import: optional:configserver:http://localhost:8088
  datasource:
    url: jdbc:mysql://localhost:3306/blogs
    username: pdursley
    password: Q1234qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  kafka:
    consumer:
      group-id: "default"
  topic:
    name: blogs
